version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
#  haproxy:
#    container_name: haproxy
#    image: haproxytech/haproxy-alpine:2.4
#    ports:
#      - "8081:8081"
#      - "8404:8404"
#    volumes:
#      - ./scripts/haproxy:/usr/local/etc/haproxy:ro
#    networks:
#      - mynetwork
  
networks:
  mynetwork:
    driver: bridge